/**
 * Tests for `createLlmCodeWriter` — verifies prompt rendering, JSON parsing,
 * and the typed error path used by `LlmImplementer` for retry feedback.
 */
import { describe, expect, test } from "bun:test";

import { createMockProvider } from "../../../llm/mock.ts";
import type { ToolManifest } from "../../../core/types.ts";
import {
  LlmCodeWriterError,
  STAGE7_LLM_PROMPT_STAGE_ID,
  STAGE7_LLM_PROMPT_VERSION,
  createLlmCodeWriter,
} from "./code-writer.ts";

function manifest(overrides: Partial<ToolManifest> = {}): ToolManifest {
  return {
    name: "ingredient_substitute",
    version: "0.1.0",
    description:
      "Suggest substitutes for an ingredient with notes on flavor and ratio.",
    whenToUse:
      "When the user asks for an alternative to a specific ingredient.",
    returnsSummary:
      "Ranked list of substitutes with ratio guidance and trade-off notes.",
    inputSchema: {
      type: "object",
      properties: { ingredient: { type: "string" } },
      required: ["ingredient"],
    },
    outputSchema: {
      type: "object",
      properties: {
        ingredient: { type: "string" },
        substitutes: { type: "array" },
      },
      required: ["ingredient", "substitutes"],
    },
    capabilities: { network: [], fs: "read", subprocess: [], secrets: [] },
    volatilityClass: "static",
    freshness: {
      cachePolicy: "manual-refresh",
      ttlSeconds: null,
      sourceTimestamp: false,
    },
    knowledgeUsage: { facts: true, ftsQuery: "substitute {q}", embeddings: false },
    sourceDependencies: [],
    sampleUrls: [],
    examples: [
      {
        description: "buttermilk has a substitute",
        input: { ingredient: "buttermilk" },
        expectedShape: "match-outputSchema",
      },
    ],
    designedBy: { model: "claude-sonnet-4", promptVersion: "06-tool-design/v1" },
    disabled: false,
    ...overrides,
  };
}

const VALID_IMPL = `// AUTO-GENERATED by almanac Stage 7.\nexport default async function f(_i: any, _c: any): Promise<any> { return { ok: false, error: { code: "stub", message: "stub", retryable: false } }; }\n`;
const VALID_TEST = `// AUTO-GENERATED by almanac Stage 7.\nimport { describe, expect, test } from "bun:test";\nimport f from "./ingredient_substitute.ts";\ndescribe("f", () => { test("smoke", async () => { const r: any = await f({}, { secrets: {}, log: () => {} }); expect(r.ok).toBe(false); }); });\n`;

describe("createLlmCodeWriter", () => {
  test("advertises model + promptVersion", () => {
    const writer = createLlmCodeWriter({
      provider: createMockProvider({ defaultResponse: "{}" }),
      model: "claude-sonnet-4-5",
    });
    expect(writer.model).toBe("claude-sonnet-4-5");
    expect(writer.promptVersion).toBe(
      `${STAGE7_LLM_PROMPT_STAGE_ID}/${STAGE7_LLM_PROMPT_VERSION}`,
    );
  });

  test("happy path: parses {implCode, testCode} from JSON", async () => {
    const provider = createMockProvider({
      responses: {
        "07-tool-impl@v1": JSON.stringify({
          implCode: VALID_IMPL,
          testCode: VALID_TEST,
        }),
      },
    });
    const writer = createLlmCodeWriter({ provider });
    const result = await writer.generate({
      manifest: manifest(),
      almanacDir: "/tmp/almanac",
    });
    expect(result.code).toBe(VALID_IMPL);
    expect(result.testCode).toBe(VALID_TEST);
  });

  test("renders previousAttempt block into the user message", async () => {
    let captured = "";
    const provider = createMockProvider({
      responses: {
        "07-tool-impl@v1": JSON.stringify({
          implCode: VALID_IMPL,
          testCode: VALID_TEST,
        }),
      },
    });
    const writer = createLlmCodeWriter({
      provider,
      onRequest: (req) => {
        captured = req.messages[1]!.content;
      },
    });
    await writer.generate({
      manifest: manifest(),
      almanacDir: "/tmp/almanac",
      previousAttempt: {
        code: "broken impl",
        testCode: "broken test",
        outcome: "tsc-failed",
        diagnostics: "TS2304: Cannot find name 'foo'",
      },
    });
    expect(captured).toContain("tsc-failed");
    expect(captured).toContain("TS2304");
    expect(captured).toContain("broken impl");
  });

  test("throws LlmCodeWriterError on non-JSON response", async () => {
    const provider = createMockProvider({ defaultResponse: "not json" });
    const writer = createLlmCodeWriter({ provider });
    try {
      await writer.generate({ manifest: manifest(), almanacDir: "/tmp/x" });
      throw new Error("expected throw");
    } catch (e) {
      expect(e).toBeInstanceOf(LlmCodeWriterError);
      expect((e as LlmCodeWriterError).rawText).toBe("not json");
      expect((e as Error).message).toContain("not valid JSON");
    }
  });

  test("throws LlmCodeWriterError when shape is wrong", async () => {
    const provider = createMockProvider({
      defaultResponse: JSON.stringify({ implCode: "" }),
    });
    const writer = createLlmCodeWriter({ provider });
    try {
      await writer.generate({ manifest: manifest(), almanacDir: "/tmp/x" });
      throw new Error("expected throw");
    } catch (e) {
      expect(e).toBeInstanceOf(LlmCodeWriterError);
      expect((e as Error).message).toContain("does not match");
    }
  });

  test("strips a leading code fence around the JSON", async () => {
    const provider = createMockProvider({
      defaultResponse:
        "```json\n" +
        JSON.stringify({ implCode: VALID_IMPL, testCode: VALID_TEST }) +
        "\n```",
    });
    const writer = createLlmCodeWriter({ provider });
    const result = await writer.generate({
      manifest: manifest(),
      almanacDir: "/tmp/x",
    });
    expect(result.code).toBe(VALID_IMPL);
  });
});
