/**
 * Canonical templates for the four default tools.
 *
 * Per `docs/design.md` §5, every almanac ships with the same four tools:
 *
 *   - query_facts         — FTS5 lookup against the indexed fact store
 *   - fetch_official_docs — capability-gated GET to a manifest-configured URL
 *   - web_search_recent   — recent-bias web search (DuckDuckGo HTML)
 *   - latest_releases     — GitHub releases for a manifest-configured repo
 *
 * Each entry below is a pair of *string sources*:
 *   - `implCode`  → written to `<almanacDir>/tools/<name>.ts`
 *   - `testCode`  → written to `<almanacDir>/tools/<name>.test.ts`
 *
 * The implementations are intentionally self-contained: they avoid imports
 * from the almanac source tree (which doesn't exist on disk after compile)
 * and only rely on globals (`fetch`, `URL`) plus the runtime-provided
 * `ctx.knowledge` / `ctx.fetch`. Bun loads them via the runtime's
 * `loadTool()` dynamic import.
 *
 * The smoke tests run with `bun test`, mock any network/knowledge access,
 * and assert envelope shape + key invariants.
 */

import type { ToolName } from "../../../core/types.ts";

// ──────────────────────────────────────────────────────────────────────────────
// Template registry
// ──────────────────────────────────────────────────────────────────────────────

export interface DefaultToolTemplate {
  /** TypeScript source of the implementation file (.ts). */
  implCode: string;
  /** TypeScript source of the smoke-test file (.test.ts). */
  testCode: string;
}

// The registry itself is exported from the bottom of this file to satisfy
// TypeScript's temporal-dead-zone rule (templates referenced by const must be
// declared first). See `DEFAULT_TOOL_TEMPLATES` below.

// ──────────────────────────────────────────────────────────────────────────────
// 1. query_facts
// ──────────────────────────────────────────────────────────────────────────────

const QUERY_FACTS_IMPL = `// AUTO-GENERATED by almanac Stage 7 (TemplateImplementer). Do not edit by hand.
//
// query_facts — FTS5 lookup against the indexed fact store.
//
// input:  { q: string, limit?: number, freshnessClass?: "static" | "slow" }
// output: { hits: Array<{ id, text, type, source, freshnessClass, validUntil }> }

export async function queryFacts(input: any, ctx: any): Promise<any> {
  if (!ctx || !ctx.knowledge || typeof ctx.knowledge.searchFacts !== "function") {
    return {
      ok: false,
      error: {
        code: "knowledge-missing",
        message: "query_facts requires the knowledge index; call \\\`almanac update\\\` to rebuild.",
        retryable: false,
      },
    };
  }

  const q = typeof input?.q === "string" ? input.q.trim() : "";
  if (q.length === 0) {
    return {
      ok: false,
      error: { code: "bad-input", message: "input.q must be a non-empty string", retryable: false },
    };
  }

  const limit = Math.max(1, Math.min(50, Number.isFinite(input?.limit) ? Number(input.limit) : 10));
  const opts: any = { limit, notExpiredAt: new Date().toISOString() };
  if (input?.freshnessClass === "static" || input?.freshnessClass === "slow") {
    opts.freshnessClass = input.freshnessClass;
  }

  let hits = await ctx.knowledge.searchFacts(q, opts);
  if (hits.length === 0) {
    for (const fallbackQ of fallbackQueries(q)) {
      hits = await ctx.knowledge.searchFacts(fallbackQ, opts);
      if (hits.length > 0) break;
    }
  }

  if (hits.length === 0) {
    return {
      ok: false,
      error: { code: "no-results", message: \`no facts matched "\${q}"\`, retryable: false },
    };
  }

  const nowIso = new Date().toISOString();
  const citations: any[] = [];
  const seenSources = new Set<string>();
  for (const h of hits) {
    if (seenSources.has(h.source.sourceId)) continue;
    seenSources.add(h.source.sourceId);
    citations.push({
      sourceId: h.source.sourceId,
      url: h.source.url,
      fetchedAt: h.extractedAt ?? nowIso,
      excerpt: h.source.excerpt,
    });
    if (citations.length >= 10) break;
  }

  // Determine the most volatile class among the hits to drive freshness.
  let anySlow = false;
  for (const h of hits) {
    if (h.freshnessClass === "slow") {
      anySlow = true;
      break;
    }
  }

  return {
    ok: true,
    data: {
      hits: hits.map((h: any) => ({
        id: h.id,
        text: h.text,
        type: h.type,
        source: { sourceId: h.source.sourceId, url: h.source.url },
        freshnessClass: h.freshnessClass,
        validUntil: h.validUntil,
        confidence: h.confidence,
      })),
    },
    citations,
    freshness: anySlow
      ? { class: "slow", maxAge: 2592000, staleness: "fresh" }
      : { class: "static", maxAge: null, staleness: "fresh" },
  };
}

function fallbackQueries(q: string): string[] {
  const seen = new Set<string>();
  const tokens: string[] = [];
  for (const token of q.match(/[A-Za-z0-9_']+/g) ?? []) {
    const key = token.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    tokens.push(token);
  }
  if (tokens.length <= 1) return [];

  const out: string[] = [];
  const original = q.trim().toLowerCase();
  for (let size = Math.min(3, tokens.length - 1); size >= 1; size -= 1) {
    for (let start = 0; start + size <= tokens.length; start += 1) {
      const candidate = tokens.slice(start, start + size).join(" ");
      if (candidate.toLowerCase() === original) continue;
      out.push(candidate);
      if (out.length >= 8) return out;
    }
  }
  return out;
}

export default queryFacts;
`;

const QUERY_FACTS_TEST = `// AUTO-GENERATED by almanac Stage 7. Smoke test for query_facts.

import { describe, expect, test } from "bun:test";

import queryFacts from "./query_facts.ts";

function fakeKnowledge(facts: any[]) {
  return {
    searchFacts: async (q: string) => facts.filter((f: any) => f.text.toLowerCase().includes(q.toLowerCase())),
    getFactById: async (id: string) => facts.find((f: any) => f.id === id) ?? null,
  };
}

const sampleFact = {
  id: "01HZZZZZZZZZZZZZZZZZZZZZZZ",
  text: "Pasta cooks faster in salted boiling water.",
  type: "fact",
  entities: ["pasta"],
  source: {
    sourceId: "src-cooking-001",
    contentHash: "a".repeat(64),
    url: "https://example.com/pasta",
    excerpt: "Salt the water before adding pasta.",
  },
  freshnessClass: "static",
  validUntil: null,
  confidence: 0.9,
  extractedAt: "2026-01-01T00:00:00.000Z",
  extractor: { model: "test", promptVersion: "v1" },
};

describe("query_facts", () => {
  test("returns ok envelope with hits + citations on a match", async () => {
    const ctx: any = { knowledge: fakeKnowledge([sampleFact]), secrets: {}, log: () => {} };
    const r = await queryFacts({ q: "pasta" }, ctx);
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.data.hits.length).toBe(1);
      expect(r.citations[0].sourceId).toBe("src-cooking-001");
      expect(r.freshness.class).toBe("static");
    }
  });

  test("returns no-results error when nothing matches", async () => {
    const ctx: any = { knowledge: fakeKnowledge([sampleFact]), secrets: {}, log: () => {} };
    const r = await queryFacts({ q: "soufflé" }, ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("no-results");
  });

  test("returns knowledge-missing when ctx.knowledge is absent", async () => {
    const r = await queryFacts({ q: "anything" }, { secrets: {}, log: () => {} } as any);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("knowledge-missing");
  });

  test("rejects empty input.q with bad-input", async () => {
    const ctx: any = { knowledge: fakeKnowledge([sampleFact]), secrets: {}, log: () => {} };
    const r = await queryFacts({ q: "" }, ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("bad-input");
  });
});
`;

// ──────────────────────────────────────────────────────────────────────────────
// 2. fetch_official_docs
// ──────────────────────────────────────────────────────────────────────────────

const FETCH_DOCS_IMPL = `// AUTO-GENERATED by almanac Stage 7. fetch_official_docs.
//
// input:  { url: string }
// output: { url, status, contentType, body, fetchedAt }

export async function fetchOfficialDocs(input: any, ctx: any): Promise<any> {
  if (!ctx || typeof ctx.fetch !== "function") {
    return {
      ok: false,
      error: {
        code: "network-not-allowed",
        message: "fetch_official_docs requires network capability; check the manifest's capabilities.network allowlist.",
        retryable: false,
      },
    };
  }
  const url = typeof input?.url === "string" ? input.url : "";
  if (url.length === 0) {
    return { ok: false, error: { code: "bad-input", message: "input.url is required", retryable: false } };
  }

  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return { ok: false, error: { code: "bad-input", message: \`invalid url: "\${url}"\`, retryable: false } };
  }

  const fetchedAt = new Date().toISOString();
  let res: Response;
  try {
    res = await ctx.fetch(url, { redirect: "follow" });
  } catch (e: any) {
    const isAllowlist = e && e.name === "NetworkNotAllowedError";
    return {
      ok: false,
      error: {
        code: isAllowlist ? "network-not-allowed" : "fetch-failed",
        message: (e && e.message ? String(e.message) : "fetch failed").slice(0, 500),
        retryable: !isAllowlist,
      },
    };
  }

  const status = res.status;
  if (status >= 400) {
    return {
      ok: false,
      error: {
        code: status >= 500 ? "server-error" : "client-error",
        message: \`HTTP \${status} from \${url}\`,
        retryable: status >= 500 || status === 429,
      },
    };
  }

  const contentType = res.headers.get("content-type") ?? "application/octet-stream";
  const body = await res.text();
  const truncated = body.length > 200_000 ? body.slice(0, 200_000) : body;

  return {
    ok: true,
    data: {
      url,
      status,
      contentType,
      body: truncated,
      truncated: body.length > truncated.length,
      fetchedAt,
    },
    citations: [{ sourceId: hostnameToSourceId(parsed.hostname), url, fetchedAt }],
    freshness: { class: "slow", maxAge: 2592000, staleness: "fresh" },
  };
}

function hostnameToSourceId(host: string): string {
  return ("src-" + host.replace(/[^a-z0-9-]+/gi, "-")).toLowerCase().slice(0, 64);
}

export default fetchOfficialDocs;
`;

const FETCH_DOCS_TEST = `// AUTO-GENERATED by almanac Stage 7. Smoke test for fetch_official_docs.

import { describe, expect, test } from "bun:test";

import fetchOfficialDocs from "./fetch_official_docs.ts";

function mockFetch(response: { status: number; body: string; contentType?: string }) {
  return async (_url: string) => {
    return new Response(response.body, {
      status: response.status,
      headers: { "content-type": response.contentType ?? "text/html" },
    });
  };
}

describe("fetch_official_docs", () => {
  test("returns ok envelope on 200", async () => {
    const ctx: any = { fetch: mockFetch({ status: 200, body: "<html>doc</html>" }), secrets: {}, log: () => {} };
    const r = await fetchOfficialDocs({ url: "https://example.com/x" }, ctx);
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.data.status).toBe(200);
      expect(r.data.body).toContain("doc");
      expect(r.citations[0].url).toBe("https://example.com/x");
      expect(r.freshness.class).toBe("slow");
    }
  });

  test("maps 404 to client-error envelope", async () => {
    const ctx: any = { fetch: mockFetch({ status: 404, body: "" }), secrets: {}, log: () => {} };
    const r = await fetchOfficialDocs({ url: "https://example.com/missing" }, ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("client-error");
  });

  test("maps 503 to retryable server-error envelope", async () => {
    const ctx: any = { fetch: mockFetch({ status: 503, body: "" }), secrets: {}, log: () => {} };
    const r = await fetchOfficialDocs({ url: "https://example.com/down" }, ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) {
      expect(r.error.code).toBe("server-error");
      expect(r.error.retryable).toBe(true);
    }
  });

  test("returns network-not-allowed when ctx.fetch is absent", async () => {
    const r = await fetchOfficialDocs({ url: "https://example.com" }, { secrets: {}, log: () => {} } as any);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("network-not-allowed");
  });
});
`;

// ──────────────────────────────────────────────────────────────────────────────
// 3. web_search_recent
// ──────────────────────────────────────────────────────────────────────────────

const WEB_SEARCH_IMPL = `// AUTO-GENERATED by almanac Stage 7. web_search_recent.
//
// Recent-bias web search using DuckDuckGo's HTML endpoint (no API key).
// input:  { q: string, limit?: number }
// output: { results: Array<{ title, url, snippet }>, query, fetchedAt }

export async function webSearchRecent(input: any, ctx: any): Promise<any> {
  if (!ctx || typeof ctx.fetch !== "function") {
    return {
      ok: false,
      error: {
        code: "network-not-allowed",
        message: "web_search_recent requires network capability for duckduckgo.com.",
        retryable: false,
      },
    };
  }
  const q = typeof input?.q === "string" ? input.q.trim() : "";
  if (q.length === 0) {
    return { ok: false, error: { code: "bad-input", message: "input.q must be a non-empty string", retryable: false } };
  }
  const limit = Math.max(1, Math.min(20, Number.isFinite(input?.limit) ? Number(input.limit) : 5));

  const fetchedAt = new Date().toISOString();
  const ddgUrl = \`https://html.duckduckgo.com/html/?q=\${encodeURIComponent(q)}\`;

  let res: Response;
  try {
    res = await ctx.fetch(ddgUrl, {
      headers: { "user-agent": "Mozilla/5.0 (almanac/0.1) AppleWebKit/537.36" },
    });
  } catch (e: any) {
    return {
      ok: false,
      error: {
        code: e?.name === "NetworkNotAllowedError" ? "network-not-allowed" : "fetch-failed",
        message: String(e?.message ?? "fetch failed").slice(0, 500),
        retryable: e?.name !== "NetworkNotAllowedError",
      },
    };
  }
  if (res.status >= 400) {
    return {
      ok: false,
      error: {
        code: res.status >= 500 ? "server-error" : "client-error",
        message: \`DuckDuckGo returned HTTP \${res.status}\`,
        retryable: res.status >= 500 || res.status === 429,
      },
    };
  }
  const html = await res.text();
  const results = parseDuckDuckGoResults(html, limit);

  if (results.length === 0) {
    return {
      ok: false,
      error: { code: "no-results", message: \`no web results for "\${q}"\`, retryable: true },
    };
  }

  return {
    ok: true,
    data: { query: q, fetchedAt, results },
    citations: [{ sourceId: "src-duckduckgo", url: ddgUrl, fetchedAt }],
    freshness: { class: "fast", maxAge: 86400, staleness: "fresh" },
  };
}

function parseDuckDuckGoResults(html: string, limit: number): Array<{ title: string; url: string; snippet: string }> {
  const out: Array<{ title: string; url: string; snippet: string }> = [];
  // DDG HTML uses .result__a for links and .result__snippet for snippets.
  const blockRe = /<a[^>]+class=\\"result__a\\"[^>]+href=\\"([^\\"]+)\\"[^>]*>([\\s\\S]*?)<\\/a>[\\s\\S]*?<a[^>]+class=\\"result__snippet\\"[^>]*>([\\s\\S]*?)<\\/a>/g;
  let m: RegExpExecArray | null;
  while ((m = blockRe.exec(html)) !== null && out.length < limit) {
    const rawUrl = decodeDdgUrl(m[1] ?? "");
    if (!rawUrl) continue;
    out.push({
      url: rawUrl,
      title: stripHtml(m[2] ?? "").slice(0, 200),
      snippet: stripHtml(m[3] ?? "").slice(0, 500),
    });
  }
  return out;
}

function decodeDdgUrl(u: string): string {
  // DDG wraps result links as "/l/?uddg=<encoded-url>".
  try {
    if (u.startsWith("//")) u = "https:" + u;
    if (u.startsWith("/")) u = "https://duckduckgo.com" + u;
    const url = new URL(u);
    const ud = url.searchParams.get("uddg");
    if (ud) return decodeURIComponent(ud);
    return url.toString();
  } catch {
    return "";
  }
}

function stripHtml(s: string): string {
  return s.replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").trim();
}

export default webSearchRecent;
`;

const WEB_SEARCH_TEST = `// AUTO-GENERATED by almanac Stage 7. Smoke test for web_search_recent.

import { describe, expect, test } from "bun:test";

import webSearchRecent from "./web_search_recent.ts";

const SAMPLE_HTML = \`
<html><body>
<a class="result__a" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fexample.com%2Fa">Example A</a>
<a class="result__snippet">A snippet for example A.</a>
<a class="result__a" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fexample.com%2Fb">Example B</a>
<a class="result__snippet">A snippet for example B.</a>
</body></html>
\`;

describe("web_search_recent", () => {
  test("parses DuckDuckGo HTML and returns ok envelope", async () => {
    const ctx: any = {
      fetch: async () => new Response(SAMPLE_HTML, { status: 200, headers: { "content-type": "text/html" } }),
      secrets: {},
      log: () => {},
    };
    const r = await webSearchRecent({ q: "example" }, ctx);
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.data.results.length).toBe(2);
      expect(r.data.results[0].url).toBe("https://example.com/a");
      expect(r.data.results[0].title).toContain("Example A");
      expect(r.freshness.class).toBe("fast");
      expect(r.citations[0].sourceId).toBe("src-duckduckgo");
    }
  });

  test("returns no-results when DDG HTML has no result blocks", async () => {
    const ctx: any = {
      fetch: async () => new Response("<html></html>", { status: 200, headers: { "content-type": "text/html" } }),
      secrets: {},
      log: () => {},
    };
    const r = await webSearchRecent({ q: "nothing here" }, ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("no-results");
  });

  test("returns network-not-allowed when ctx.fetch is absent", async () => {
    const r = await webSearchRecent({ q: "x" }, { secrets: {}, log: () => {} } as any);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("network-not-allowed");
  });
});
`;

// ──────────────────────────────────────────────────────────────────────────────
// 4. latest_releases
// ──────────────────────────────────────────────────────────────────────────────

const LATEST_RELEASES_IMPL = `// AUTO-GENERATED by almanac Stage 7. latest_releases.
//
// Fetches recent releases for one GitHub repository.
// input:  { owner: string, repo: string, limit?: number }
// output: { repo, releases: Array<{ tagName, name, publishedAt, url, prerelease, draft }> }

export async function latestReleases(input: any, ctx: any): Promise<any> {
  if (!ctx || typeof ctx.fetch !== "function") {
    return {
      ok: false,
      error: {
        code: "network-not-allowed",
        message: "latest_releases requires network capability for api.github.com.",
        retryable: false,
      },
    };
  }
  const owner = typeof input?.owner === "string" ? input.owner.trim() : "";
  const repo = typeof input?.repo === "string" ? input.repo.trim() : "";
  if (!owner || !repo) {
    return {
      ok: false,
      error: { code: "bad-input", message: "input.owner and input.repo are required", retryable: false },
    };
  }
  const limit = Math.max(1, Math.min(30, Number.isFinite(input?.limit) ? Number(input.limit) : 10));

  const fetchedAt = new Date().toISOString();
  const url = \`https://api.github.com/repos/\${encodeURIComponent(owner)}/\${encodeURIComponent(repo)}/releases?per_page=\${limit}\`;
  const headers: Record<string, string> = {
    accept: "application/vnd.github+json",
    "x-github-api-version": "2022-11-28",
    "user-agent": "almanac/0.1",
  };
  if (ctx.secrets && typeof ctx.secrets.GITHUB_TOKEN === "string" && ctx.secrets.GITHUB_TOKEN.length > 0) {
    headers.authorization = "Bearer " + ctx.secrets.GITHUB_TOKEN;
  }

  let res: Response;
  try {
    res = await ctx.fetch(url, { headers });
  } catch (e: any) {
    return {
      ok: false,
      error: {
        code: e?.name === "NetworkNotAllowedError" ? "network-not-allowed" : "fetch-failed",
        message: String(e?.message ?? "fetch failed").slice(0, 500),
        retryable: e?.name !== "NetworkNotAllowedError",
      },
    };
  }
  if (res.status >= 400) {
    return {
      ok: false,
      error: {
        code: res.status >= 500 ? "server-error" : res.status === 404 ? "not-found" : "client-error",
        message: \`GitHub API returned HTTP \${res.status} for \${owner}/\${repo}\`,
        retryable: res.status >= 500 || res.status === 429 || res.status === 403,
      },
    };
  }
  let data: any;
  try {
    data = await res.json();
  } catch (e: any) {
    return {
      ok: false,
      error: { code: "bad-response", message: "GitHub returned non-JSON", retryable: false },
    };
  }
  if (!Array.isArray(data)) {
    return {
      ok: false,
      error: { code: "bad-response", message: "expected an array of releases", retryable: false },
    };
  }
  const releases = data.map((r: any) => ({
    tagName: typeof r.tag_name === "string" ? r.tag_name : "",
    name: typeof r.name === "string" ? r.name : "",
    publishedAt: typeof r.published_at === "string" ? r.published_at : null,
    url: typeof r.html_url === "string" ? r.html_url : "",
    prerelease: r.prerelease === true,
    draft: r.draft === true,
  }));

  return {
    ok: true,
    data: { repo: \`\${owner}/\${repo}\`, fetchedAt, releases },
    citations: [
      {
        sourceId: ("src-github-" + owner + "-" + repo).toLowerCase().slice(0, 64).replace(/[^a-z0-9-]+/g, "-"),
        url: \`https://github.com/\${owner}/\${repo}/releases\`,
        fetchedAt,
        sourceTimestamp: releases[0]?.publishedAt ?? undefined,
      },
    ],
    freshness: { class: "fast", maxAge: 86400, staleness: "fresh" },
  };
}

export default latestReleases;
`;

const LATEST_RELEASES_TEST = `// AUTO-GENERATED by almanac Stage 7. Smoke test for latest_releases.

import { describe, expect, test } from "bun:test";

import latestReleases from "./latest_releases.ts";

const SAMPLE_RELEASES = [
  {
    tag_name: "v1.2.3",
    name: "Release 1.2.3",
    published_at: "2026-01-15T00:00:00Z",
    html_url: "https://github.com/octo/repo/releases/tag/v1.2.3",
    prerelease: false,
    draft: false,
  },
  {
    tag_name: "v1.2.2",
    name: "Release 1.2.2",
    published_at: "2026-01-01T00:00:00Z",
    html_url: "https://github.com/octo/repo/releases/tag/v1.2.2",
    prerelease: true,
    draft: false,
  },
];

describe("latest_releases", () => {
  test("parses GitHub releases and returns ok envelope", async () => {
    const ctx: any = {
      fetch: async () => new Response(JSON.stringify(SAMPLE_RELEASES), {
        status: 200,
        headers: { "content-type": "application/json" },
      }),
      secrets: {},
      log: () => {},
    };
    const r = await latestReleases({ owner: "octo", repo: "repo" }, ctx);
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.data.releases.length).toBe(2);
      expect(r.data.releases[0].tagName).toBe("v1.2.3");
      expect(r.data.releases[1].prerelease).toBe(true);
      expect(r.freshness.class).toBe("fast");
      expect(r.citations[0].sourceTimestamp).toBe("2026-01-15T00:00:00Z");
    }
  });

  test("forwards GITHUB_TOKEN as a Bearer header when present", async () => {
    let captured: any = null;
    const ctx: any = {
      fetch: async (_url: string, init: any) => {
        captured = init;
        return new Response("[]", { status: 200, headers: { "content-type": "application/json" } });
      },
      secrets: { GITHUB_TOKEN: "ghp_test" },
      log: () => {},
    };
    await latestReleases({ owner: "octo", repo: "repo" }, ctx);
    expect(captured?.headers?.authorization).toBe("Bearer ghp_test");
  });

  test("maps 404 to not-found envelope", async () => {
    const ctx: any = {
      fetch: async () => new Response("", { status: 404 }),
      secrets: {},
      log: () => {},
    };
    const r = await latestReleases({ owner: "octo", repo: "missing" }, ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("not-found");
  });

  test("rejects missing owner/repo as bad-input", async () => {
    const ctx: any = { fetch: async () => new Response("[]", { status: 200 }), secrets: {}, log: () => {} };
    const r = await latestReleases({ owner: "", repo: "x" }, ctx);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.code).toBe("bad-input");
  });
});
`;

// ──────────────────────────────────────────────────────────────────────────────
// Registry (declared after all const sources to satisfy TDZ).
// ──────────────────────────────────────────────────────────────────────────────

export const DEFAULT_TOOL_TEMPLATES: Readonly<
  Record<ToolName, DefaultToolTemplate>
> = {
  query_facts: { implCode: QUERY_FACTS_IMPL, testCode: QUERY_FACTS_TEST },
  fetch_official_docs: { implCode: FETCH_DOCS_IMPL, testCode: FETCH_DOCS_TEST },
  web_search_recent: { implCode: WEB_SEARCH_IMPL, testCode: WEB_SEARCH_TEST },
  latest_releases: { implCode: LATEST_RELEASES_IMPL, testCode: LATEST_RELEASES_TEST },
};
